name: Continuous Integration

on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build
        run: go build -v

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

      - uses: ko-build/setup-ko@v0.9

      - name: Push image
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: ko build --tags=edge --sbom=none --bare
